# This is a basic workflow to help you get started with Actions

name: Docker Build & Push

on:
    push:
        tags:
            - "*"
    workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
    DOCKER_USERNAME: retnil
    DOCKER_CONTAINER_NAME: caddy-cloudflare
    DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              if: ${{ !github.event.act }} # skip during local actions testing

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Prepare
              if: success()
              id: prepare
              run: |
                  TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
                  echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
                  echo "DOCKER_PLATFORM=${DOCKER_TARGET_PLATFORM}" >> $GITHUB_ENV

            - name: Test Tag
              run: echo "Image Tag is: ${{ env.TAG }}"
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build container and Push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
                  push: true
                  tags: |
                      ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ env.TAG }}
                      ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
